name: quantum-computing-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - qiskit=1.2.4
  - qiskit-ibm-runtime=0.30.0
  - qiskit-aer=0.15.1
  - pylatexenc=2.10
  - pennylane=0.37.0
  - tensorflow=2.15
  - silence-tensorflow